image: continuumio/miniconda3:latest

stages:
  - build
  - test

before_script:
  - source activate ./env

build:
  stage: build
  before_script:
    - echo "Stops attempt to activate env before env is built..."
  script:
    - conda env create --file environment.yml --prefix env
    - source activate ./env
    - poetry install --with dev
  artifacts:
    expire_in: 1 hour
    paths:
      - env

safety:
  stage: test
  script:
    - poetry run safety check

lint:
  stage: test
  script:
    - poetry run lint

test:
  stage: test
  script:
    - poetry run tests
  coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
  artifacts:
    expire_in: 1 hour
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
