image: code.usgs.gov:5001/devops/images/usgs/python:3.9

cache:
  paths:
    - .venv

test:
  stage: test
  before_script:
    - pip install poetry
    - poetry config virtualenvs.in-project true
    - poetry install --with dev
  script:
    - poetry run tests
    - poetry run lint
  coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
