image: python:3.11

stages:
  - build
  - test

build:
  stage: build
  script:
    - pip install poetry
    - poetry install --with dev

safety:
  stage: test
  script:
    - poetry run safety check

lint:
  stage: test
  script:
    - poetry run lint

test:
  stage: test
  script:
    - poetry run tests
  coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
  artifacts:
    expire_in: 1 hour
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
