image: code.usgs.gov:5001/devops/images/usgs/python:3.9

stages:
  - build
  - lint
  - test

cache:
  paths:
    - .venv

build:
  stage: build
  script:
    - pip install poetry
    - poetry config virtualenvs.in-project true
    - poetry install --with dev

lint:
  stage: lint
  script:
    - poetry run lint

test:
  stage: test
  script:
    - poetry run tests
  coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
