image: python:3.9

test:
  stage: test
  variables:
    MIN_COVERAGE: 95
  script:
    - pip install numpy
    - pip install nptyping
    - pip install rasterio
    - pip install pytest
    - pip install pytest-cov
    - pip install coverage

    - pytest tests/test_errors.py --cov=dfha.errors --cov-fail-under=$MIN_COVERAGE --cov-append
    - pytest tests/test_utils.py --cov=dfha.utils --cov-fail-under=$MIN_COVERAGE --cov-append
    - pytest tests/test_validate.py --cov=dfha.validate --cov-fail-under=$MIN_COVERAGE --cov-append

  coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'